generate_plot_task:
  description: >
    Generate a plot for a short video - 20 seconds. It should be some interseting fact or story about a given topic.
    plot should be small, simple and easy to understand. Not boring.
  expected_output: >
    A plot for a given topic.
  agent: plot_generator

generate_video_task:
  description: >
    Generate a XML file about the plot. Only output the XML file. No other text or comments.
    Make sure to use the correct animation type.
    Make sure that text in <text> tag is not too long.
    If text is too long, split it into multiple scenes.
    The XML file should be in the format of the example below. Fields that exists: text, start_time, duration, animation.
    You have to use stickers. Stickers are set with <sticker> tag. They have image_path, start_time, duration, animation_type, start_position, end_position fields.
    Stickers paths:
      idle.png - idle sticker, simple stickers without any emotions and positions.
    Animation fields is optional. Use animations that suit the text, plot and video.
  expected_output: >
    The XML file should be in the format of the example below. Fields that exists: text, start_time, duration, animation.
    Animation fields is optional. Use animations that suit the text, plot and video.
    No other text or comments.
    No additional fields.
    Example:
    <plot>
    <scene>
        <text>Did you know microwaves were invented by accident?</text>
        <start_time>0</start_time>
        <duration>5</duration>
        <animation_type>fade_in</animation_type>
    </scene>
    <sticker>
        <image_path>sticker1.png</image_path>
        <start_time>2</start_time>
        <duration>5</duration>
        <animation_type>move</animation_type>
        <start_position>100,100</start_position>
        <end_position>500,500</end_position>
    </sticker>
    <scene>
        <text>In the 1940s, a scientist unwittingly melted a chocolate bar...</text>
        <start_time>5</start_time>
        <duration>5</duration>
        <animation_type>zoom</animation_type>
        <start_scale>0.8</start_scale>
        <end_scale>1.0</end_scale>
    </scene>
    </plot>
  agent: video_generator
  context: [generate_plot_task]

make_video_task:
  description: >
    Use the MakeVideoTool to make a video from the XML file. Use tool only once.
  expected_output: >
    Status of actions.
  agent: video_maker
  context: [generate_video_task]
