tweets_searcher_task:
  description: >
    You have extensive knowledge about {domain}. Your goal is to brainstorm fresh, unique, and trending topics that are highly engaging. Each response should provide a completely new idea within the domain, avoiding repetition or previously generated topics. Search for tweets related to the topic. Generate a topic, not more than 3 words. Use topic for search.
  expected_output: >
    A list of tweets with their ids.
  agent: tweets_searcher

tweets_reader_task:
  description: >
    You are given a JSON with tweets.
    # INSTRUCTIONS: Determine actions for {agentName} (@{twitterUserName}) based on:
    {bio}
    {domain}

    Guidelines:
    - Highly selective engagement
    - Direct mentions are priority
    - Skip: low-effort content, off-topic, repetitive

    Actions (respond only with tags):
    [RETWEET] - Perfect character alignment (9/10)
    [QUOTE] - Can add unique value (8/10)

    Tweets are given in JSON format.
    Respond with qualifying action tags only. Choose any combination of [RETWEET] and [QUOTE]that are appropriate. Each action must be on its own line. Your response must only include the chosen actions.
    Make sure that tweets are not scam, contains true information.
  expected_output: >
    A list of actions with their ids. No other text. You have to include ids in your response. It is very important.
    Example:
    [RETWEET] 1234567890
    [QUOTE] 1234567890 [tweet text]

    If you don't have any actions to take, respond with an empty list.
    If you don't know the id of the tweet, respond with an empty list.
    You can use action only once. You can use [RETWEET] and [QUOTE] only once. It is very important.
  agent: tweets_reader
  context: [tweets_searcher_task]

tweets_quote_task:
  description: >
    You are given a list of tweets with their ids.
    You have to complete actions on tweets.
    Use tool to quote the tweet.
    For quote, you have to add comment to the tweet. Generate comment text using tweet content.   # Areas of Expertise
    {knowledge}

    About {agentName} (@{twitterUserName}):
    {bio}
    {lore}
    {topics}

    {characterPostExamples}


    # Task: Generate a post in the voice and style and perspective of {agentName} @{twitterUserName}.
    Write a post that is (choose randomly from the list of adjectives) {adjectives} about topic (without mentioning topic directly), from the perspective of {agentName}. Do not add commentary or acknowledge this request, just write the post.
    Your response should be 1, 2, or 3 sentences (choose the length at random). Number of words in sentence should be 5-7.
    Use english not higher than B2 level.
    Your response should not contain any questions. Brief, concise statements only. The total character count MUST be less than {maxTweetLength}. No emojis. Use \\n\\n (double spaces) between statements if there are multiple statements in your response.`;
    Use tool with search query topic to get information about the topic. And then use tool to visit website and get information about the topic. Use youtube tool to get video about the topic. Include it in the tweet.
  expected_output: >
    An engaging, informative tweet about topic under 280 characters in following style: 
    {style}
    For retweet, you have to retweet the tweet.
    You can use [QUOTE] only once. It is very important.
    You have to use tool to quote the tweet.
  expected_output: >
    Status of actions.
  agent: tweets_quote_writer
  context: [tweets_reader_task]


tweets_retweet_task:
  description: >
    You are given a list of tweets with their ids.
    You have to complete actions on tweets.
    Use tools to complete actions.
    For retweet, you have to retweet the tweet.
  expected_output: >
    Status of actions.
  agent: tweets_retweeter
  context: [tweets_reader_task]


logger_task:
  description: >
    Transform all infromation to a clear and easy to understand format.

  expected_output: >
    [Time]
    Topic for search.
    Ids of tweets that were found.
    Actions that were taken.
    Always use new lines to separate each line.
    Do not add any commentary or questions.
    Make it clear what is what.

    Example:
    [2025-01-01 12:00:00]
    Topic: AI LLMs
    Ids of tweets that were found: 1234567890, 1234567891, 1234567892
    Actions that were taken: [QUOTE] 1234567890, [RETWEET] 1234567891, [QUOTE] 1234567892
    
  agent: logger
  context:
    [
      tweets_searcher_task,
      tweets_reader_task,
      tweets_quote_task,
      tweets_retweet_task,
    ]
