TWITTER_ACCESS_TOKEN: 1875150669138571265-IsdJ8hah99py1w83jKZozdKgLqmU3r
TWITTER_ACCESS_TOKEN_SECRET: xUEoBO9eAy6oTeyHeM5lOKMHSU6aI02pUsBve64nQlsJW
TWITTER_ACTION_INTERVAL_MAX: 2
TWITTER_ACTION_INTERVAL_MIN: 1
TWITTER_POST_INTERVAL_MAX: 22
TWITTER_POST_INTERVAL_MIN: 12
YOUTUBE_POST_INTERVAL_MAX: 2
YOUTUBE_POST_INTERVAL_MIN: 1
client_id: 1098259257856-1bkfr683cp83gfi98l1jn6lliqnokvha.apps.googleusercontent.com
client_secret: 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
refresh_token: 1//09Y6HvZYl8CnMCgYIARAAGAkSNwF-L9IrWERpVmdaYG9kFrO2PtEfkkZEecFaUpysvjQI1NsCh3v4i_RmET8rikqujBhzrXxGHqg
scopes:
- https://www.googleapis.com/auth/youtube.upload
token: ya29.a0ARW5m75SjcFYvp86rkdKc1Lqr8IYXK1pbQMVZRiBfsKY9bT-SblodlDxn-JSjLJARtFyjzKB14Jdzw5X1mN-wvc0muqfK4y5y1H2ZPQo0GYMtxChn8URK4gF94g55HUAB3qdFcIZx9bTkJs502YX311ip_MW1f0AO_i-6PNuaCgYKAYESARISFQHGX2MiufcL8GnIcP-Pk1dPBS46WA0175
token_uri: https://oauth2.googleapis.com/token
