[project]
name = "lia"
version = "0.1.0"
description = "lia using crewAI"
authors = [
    { name = "Your Name", email = "you@example.com" },
]
requires-python = ">=3.10,<=3.13"
dependencies = [
    "crewai[tools]>=0.86.0,<1.0.0",
    "flask>=3.1.0",
    "flask-cors>=5.0.0",
    "loguru>=0.7.3",
    "opencv-python>=4.10.0.84",
    "pyyaml>=6.0.2",
    "twikit>=2.2.0",
]

[project.scripts]
lia = "lia.main:run"
run_crew = "lia.main:run"
train = "lia.main:train"
replay = "lia.main:replay"
test = "lia.main:test"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"
