topic_researcher_task:
  description: >
    You have extensive knowledge about {domain}. Your goal is to brainstorm fresh, unique topics that are highly engaging. Each response should provide a completely new idea within the domain, avoiding repetition or previously generated topics. 
    Exclude following topics: {exclude_topics}.
    Topic must be intersting for user, some interesting fact, famous story, person, place, controversial topic, etc.
    Generate a topic.

  expected_output: >
    One topic. No additional text.
  agent: topic_researcher

plot_maker_task:
  description: >
    Tell a fact about topic. It must be real. It must be interesting fact to keep viewer's attention.
    Tell the story in duration 30 seconds. You are telling the story to a viewer, you must grab his attention. Use very easy words, language.
    This story will be told in a video with AI voice. Do not use any symbols or any special characters. Make it easy for AI to generate voice.
    Numbers write in numbers, never write numbers in words.
    Do not refer to viewer. Do not make anything to the end.
    Each scene must be 5 seconds. Not longer!
    The image should be related to the text and reflect what is written in the text.
    ImageType is either "Real" or "AI". Real means that image can be found on the internet. AI means that image will be generated by AI.
    Use real images when the subject exists in the real world and accuracy or authenticity is required, such as:
    A specific person, animal, object, or place that can be found on the internet or is well-known.
    Situations where the image needs to reflect actual events, real-world references, or verifiable subjects (e.g., news, research, or legal documentation).
    Scenarios where credibility or traceability is critical, and the image must match existing, real-world expectations.
    Describe image for each scene that will be reliable for the text. Your description will be used by AI to generate images. Also if image can be found on the internet, describe it so search engine can find it and it will be used as a background.
    Text will be used for AI to generate voice. Do not use any symbols or any special characters.

    Examples:
      once a group of explorers which included the famous American astronaut Neil Armstrong ventured to find out the secrets of a cave located in the eastern slopes of the Andes mountains in the year 1976 the Andes Mountains hold a very significant place in the investigation of lost Advanced civilizations from distant Antiquity it is also mentioned in the ancient Indian text the ramayana in which a group of half human half monkey-like beings set out to find the wife of Lord Rama who kidnapped by a humanoid being called ravan the caves in the Andes are described as the gateways to prehistoric civilizations by ancient cultures in India and meso America and you will be shocked to know that when Neil Armstrong and his team went into that cave known as the qua de losos they found very intricate and deep tunnels which still remain unexplored the native shuar people guard this cave and its hidden secrets and no one can enter it without their permission so what could be hiding beneath those tunnels
      what if I tell you that the ancient Indians had found a way to voluntarily complete the biological evolution of a human being they developed a very powerful and effective system known as the Kundalini Yoga which can turn an ordinary human into a superhuman the ancient sages mapped the human body and discovered the wonders of chakras and Kundalini energy this energy is stored at the base of the spine of every human being so they devised methods to awaken it from sleep once awakened it WS Havoc if the practitioner is not sufficiently prepared therefore it is advisable to practice this yoga with adequate preparations after the Kundalini Shakti is awakened the task of the practitioner is to guide this energy to his brain and voluntarily complete his evolution in this process the practitioner gets many superhuman and extraordinary capabilities
      did you know that in India there is an ancient statue which is still breathing Yes you heard that right the main Idol of the Lakshmi narasa Temple in wadali is still breathing to this day this might sound unbelievable but you can observe this phenomena by watching the flickering lamp placed in front of its face the scanda purana says that the idol was not made on Earth it was brought from a different Realm by the sage agastia as explained in my previous videos agastia was a very powerful Sage of his time he could travel through higher Realms and meet the gods so could it be possible that he brought this statue from A Different World you will be surprised to know that the surface of this statue is soft exactly like a living being
      the Rama satu or Adams bridge is one of the most intriguing Mysteries which many people from across the world have tried to understand and solve this structure dates back to thousands of years often making people wonder who or what could have made this marvelous Bridge Over the Sea followers of Hinduism believe that this bridge was constructed by Rama and Indian prince in Exile to rescue his wife Sita from Sri Lanka where she was kept confined by ravana if geologists and archaeologists are to be believed the rocks of the bridge are over 7 000 years old while The Sandbar is about 4 000 years old this implies that the Rocks were brought there from some other place it has been found that the bridge was walkable until the end of the 15th century and it was above sea level until a cyclone destroyed it in 1480. so was this structure artificially built
      it is a strange mystery that no one has been able to climb the peaks of Mount kailash; Mount kailash has an altitude of 22,028 feet and it lies in the kailash range of the trans Himalayan region; for followers of Hinduism and Buddhism it is forbidden to track the heights of this sacred Mountain; Hindus believe that it is the Abode of Lord Shiva, one of the most powerful deities in Hinduism; there is an interesting account of a team of Siberian climbers trying to climb this mountain in the past; after climbing for a certain altitude something strange and mysterious began to happen to these climbers; their hairs and Nails began to grow much faster and they felt excessive tiredness; it was like something was stopping them to climb any further so they had to abandon their adventure of trekking the kailash; after returning home all of them mysteriously died of old age

  expected_output: >
    Example of plot:
    [00:00-00:05] - Text: "First part of the text." ImageType: "Real". Image: "Description of the image for the first slide."  
    [00:05-00:10] - Text: "Second part of the text." ImageType: "AI". Image: "Description of the image for the second slide."
  agent: plot_maker
  context: [topic_researcher_task]

image_generator_task:
  description: >
    Use tool to generate or find in the internet images.
    Use tool to generate or find in the internet images.
    If ImageType is "Real", use tool to find image in the internet. When using the tool, use only key words for the image, do not use any additional text, so it will be easier to find image. Not more than 5 words. Never search collages or images with multiple objects.
    If ImageType is "AI", use tool to generate image.
    Make sure that image url is unique. If image url is not unique, use tool again to generate new image.
    After each found or generated image use FetchImageTool to check if image is fetched. It is very important! You can not proceed without all images fetched with FetchImageTool.
    If image is not fetched, use tool again to get a new image.
    If many times image is not fetched, use opposite ImageType.
    Image must be unique. Use tool again to generate new image.
    Do not proceed without all generated images.
    Split text to 3-4 words. If words are too long, split to 2-3 words.
    There must be 6 <scene> tags. Each tag has <FullText>, <TextPart>, <ImageUrl>, <ImageDescription>, <Duration> fields.
    <AudioSource> is the path to the audio file. Audio files: music.mp3
    <FullText> is the full text of the scene.
    <TextPart> is the part of the text of the scene, at least 2 words. Words cannot be repeated.
    Make sure that all <TextPart> are in <FullText>. You cannot skip any words from <FullText> in <TextPart>. All <FullText> must be in <TextPart>.
    <ImageUrl> is the url of the image of the scene.
    <ImageDescription> is the description of the image of the scene.
    <Duration> is the duration of the scene in format 00:00-00:05.


    Before giving final answer, check if all <TextPart> are in <FullText>. If not, add missing words to new <TextPart>. It is mandatory to have all <TextPart>!
    From all <TextPart> you can get <FullText>, if not, add missing words to new <FullText>. It is very important!

  expected_output: >
    All images with urls. Be very careful with urls. They must be correct. Without them video will not work.
    No additional text. Only XML.
    You must have all scenes. Do not delete anything! Use every image and text! It is very important!
    Example of output:
    <Scenes>
      <AudioSource>music.mp3</AudioSource>
      <Scene>
        <FullText>Did you know that bioluminescence is nature's own light show?</FullText>
        <TextPart>Did you know</TextPart>
        <TextPart>that bioluminescence</TextPart>
        <TextPart>nature's own light show?</TextPart>
        <ImageUrl>https://example.com/jellyfish.jpg</ImageUrl>
        <ImageDescription>A dark ocean scene with glowing jellyfish gracefully moving through the water, illuminating their surroundings.</ImageDescription>
        <Duration>00:00-00:05</Duration>
      </Scene>
      <Scene>
        <FullText>Over 2,500 species of organisms, including fireflies and some fungi, can produce their own light!</FullText>
        <TextPart>Over 2,500 species of organisms</TextPart>
        <TextPart>including fireflies and some fungi</TextPart>
        <TextPart>can produce their own light!</TextPart>
        <ImageUrl>https://example.com/firefly.jpg</ImageUrl>
        <ImageDescription>A close-up of a firefly glowing in a dark forest, showcasing its bright tail light.</ImageDescription>
        <Duration>00:05-00:10</Duration>
      </Scene>
      <Scene>
        <FullText>Bioluminescence is not the same as fluorescence; it involves chemical reactions in living organisms.</FullText>
        <TextPart>Bioluminescence is not the same as fluorescence</TextPart>
        <TextPart>it involves chemical reactions in living organisms</TextPart>
        <ImageUrl>https://example.com/chemical_reaction.jpg</ImageUrl>
        <ImageDescription>A diagram showing the chemical reaction of luciferin and luciferase that creates light, with glowing arrows.</ImageDescription>
        <Duration>00:10-00:15</Duration>
      </Scene>
      <Scene>
        <FullText>In the deep ocean, bioluminescent creatures use their glow for communication, camouflage, and attracting prey.</FullText>
        <TextPart>In the deep ocean</TextPart>
        <TextPart>bioluminescent creatures use their glow</TextPart>
        <TextPart>for communication, camouflage, and attracting prey</TextPart>
        <ImageUrl>https://example.com/underwater_ecosystem.jpg</ImageUrl>
        <ImageDescription>An underwater ecosystem filled with various bioluminescent creatures, with arrows pointing out different uses of their light.</ImageDescription>
        <Duration>00:15-00:20</Duration>
      </Scene>
      <Scene>
        <FullText>The anglerfish has a unique lure: a bioluminescent organ that attracts unsuspecting prey!</FullText>
        <TextPart>The anglerfish has a unique lure</TextPart>
        <TextPart>a bioluminescent organ that attracts unsuspecting prey</TextPart>
        <ImageUrl>https://example.com/anglerfish.jpg</ImageUrl>
        <ImageDescription>An anglerfish in its dark habitat, showcasing the glowing lure above its head.</ImageDescription>
        <Duration>00:20-00:25</Duration>
      </Scene>
      <Scene>
        <FullText>Bioluminescence could inspire new technologies, from medical applications to sustainable lighting!</FullText>
        <TextPart>Bioluminescence could inspire new technologies</TextPart>
        <TextPart>from medical applications to sustainable lighting</TextPart>
        <ImageUrl>https://example.com/futuristic_lab.jpg</ImageUrl>
        <ImageDescription>A futuristic lab with glowing bioluminescent plants and artificial lighting, symbolizing innovation.</ImageDescription>
        <Duration>00:25-00:30</Duration>
      </Scene>
    </Scenes>
  agent: image_generator
  context: [plot_maker_task]

video_maker_task:
  description: >
    Use tool to generate a video.
  expected_output: >
    Status of the video generation.
  agent: video_maker
  context: [image_generator_task]

logger_task:
  description: >
    Transform all infromation to a clear and easy to understand format.
  expected_output: >
    Example of output:
    [2025-01-01 12:00:00]
    Video title: AI LLMs
    Made plot: AI LLMs are the future #AI.
    Made images: 6 images.

  agent: logger
  context:
    [
      topic_researcher_task,
      plot_maker_task,
      image_generator_task,
      video_maker_task,
    ]

video_uploader_task:
  description: >
    Use tool to upload a video to YouTube.
  expected_output: >
    Status of the video upload.
  agent: video_uploader
  context: [video_maker_task]
